### ISSUE TITLE
roll dice error

### ISSUE THREAD

**Issue by Cuogng1201** [lvonkacsoh/Flow.Launcher.RollDice#3]
[2023-04-17.txt](https://github.com/lvonkacsoh/Flow.Launcher.RollDice/files/11247025/2023-04-17.txt)

Flow Launcher version: 1.14.0
OS Version: Microsoft Windows NT 10.0.19045.0
IntPtr Length: 8
x64: True

Python Path: C:\Users\ACER\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.8.9\pythonw.exe
Node Path: 
Date: 04/17/2023 13:36:01
Exception:
RollDice Exception: 
Websites: https://github.com/lvonkacsoh/Flow.Launcher.RollDice
Author: lvonkacsoh
Version: 1.0.1
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Traceback (most recent call last):
  File "C:\Users\ACER\AppData\Roaming\FlowLauncher\Plugins\RollDice-1.0.1\main.py", line 12, in <module>
    RollDice()
  File "C:\Users\ACER\AppData\Roaming\FlowLauncher\Plugins\RollDice-1.0.1\lib\flowlauncher\FlowLauncher.py", line 30, in __init__
    results = request_method(*request_parameters)
  File "C:\Users\ACER\AppData\Roaming\FlowLauncher\Plugins\RollDice-1.0.1\plugin\roll_dice.py", line 37, in query
    resultMap = {roll: self.roll_dice(roll) for roll in rolls}
  File "C:\Users\ACER\AppData\Roaming\FlowLauncher\Plugins\RollDice-1.0.1\plugin\roll_dice.py", line 37, in <dictcomp>
    resultMap = {roll: self.roll_dice(roll) for roll in rolls}
  File "C:\Users\ACER\AppData\Roaming\FlowLauncher\Plugins\RollDice-1.0.1\plugin\roll_dice.py", line 62, in roll_dice
    builder.build()
  File "C:\Users\ACER\AppData\Roaming\FlowLauncher\Plugins\RollDice-1.0.1\lib\dice_rolling\models\roll_builder.py", line 64, in build
    Die(self.__n_sides).roll() + self.__addition
  File "C:\Users\ACER\AppData\Roaming\FlowLauncher\Plugins\RollDice-1.0.1\lib\dice_rolling\models\die.py", line 25, in roll
    return self.rand.randint(1, self.sides)
  File "random.py", line 248, in randint
  File "random.py", line 226, in randrange
ValueError: empty range for randrange() (1, 1, 0)

 ---> System.IO.InvalidDataException: Traceback (most recent call last):
  File "C:\Users\ACER\AppData\Roaming\FlowLauncher\Plugins\RollDice-1.0.1\main.py", line 12, in <module>
    RollDice()
  File "C:\Users\ACER\AppData\Roaming\FlowLauncher\Plugins\RollDice-1.0.1\lib\flowlauncher\FlowLauncher.py", line 30, in __init__
    results = request_method(*request_parameters)
  File "C:\Users\ACER\AppData\Roaming\FlowLauncher\Plugins\RollDice-1.0.1\plugin\roll_dice.py", line 37, in query
    resultMap = {roll: self.roll_dice(roll) for roll in rolls}
  File "C:\Users\ACER\AppData\Roaming\FlowLauncher\Plugins\RollDice-1.0.1\plugin\roll_dice.py", line 37, in <dictcomp>
    resultMap = {roll: self.roll_dice(roll) for roll in rolls}
  File "C:\Users\ACER\AppData\Roaming\FlowLauncher\Plugins\RollDice-1.0.1\plugin\roll_dice.py", line 62, in roll_dice
    builder.build()
  File "C:\Users\ACER\AppData\Roaming\FlowLauncher\Plugins\RollDice-1.0.1\lib\dice_rolling\models\roll_builder.py", line 64, in build
    Die(self.__n_sides).roll() + self.__addition
  File "C:\Users\ACER\AppData\Roaming\FlowLauncher\Plugins\RollDice-1.0.1\lib\dice_rolling\models\die.py", line 25, in roll
    return self.rand.randint(1, self.sides)
  File "random.py", line 248, in randint
  File "random.py", line 226, in randrange
ValueError: empty range for randrange() (1, 1, 0)

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 300
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 300
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 316
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass135_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 839
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 840
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by lvonkacsoh** [comment]
Hello! Thanks for using my plugin. Actually I thought it would be dead haha. I recently thought about this plugin and felt like reworking it from the ground since I haven't touched it in a while ... and it clearly needs some love. I think I'll use this issue as the starting point to to so 🙂 Expect an update within the next days / weeks.

**Comment by lvonkacsoh** [comment]
first changes: [feat/rework](https://github.com/lvonkacsoh/Flow.Launcher.RollDice/tree/feat/rework).
may finish somewhen in the upcoming days/weeks.

**Comment by lvonkacsoh** [comment]
Let's just ignore, that it took almost a year but the new release is now ready to picked up by flows system. May take some hours. Hope it resolves your issue. If not feel free to let me know!
